# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  zlib_config = debug
  GLFW_config = debug
  Glad_config = debug
  ImGui_config = debug
  freeimage_config = debug
  FastNoiseSIMD_config = debug
  str_config = debug
  libarchive_config = debug
  Hazel_config = debug
  Sandbox_config = debug
  ImGui_Test_config = debug
  Sandbox2_config = debug
  Game_Design_config = debug

else ifeq ($(config),release)
  zlib_config = release
  GLFW_config = release
  Glad_config = release
  ImGui_config = release
  freeimage_config = release
  FastNoiseSIMD_config = release
  str_config = release
  libarchive_config = release
  Hazel_config = release
  Sandbox_config = release
  ImGui_Test_config = release
  Sandbox2_config = release
  Game_Design_config = release

else ifeq ($(config),dist)
  zlib_config = dist
  GLFW_config = dist
  Glad_config = dist
  ImGui_config = dist
  freeimage_config = dist
  FastNoiseSIMD_config = dist
  str_config = dist
  libarchive_config = dist
  Hazel_config = dist
  Sandbox_config = dist
  ImGui_Test_config = dist
  Sandbox2_config = dist
  Game_Design_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := zlib GLFW Glad ImGui freeimage FastNoiseSIMD str libarchive Hazel Sandbox ImGui\ Test Sandbox2 Game\ Design

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

zlib:
ifneq (,$(zlib_config))
	@echo "==== Building zlib ($(zlib_config)) ===="
	@${MAKE} --no-print-directory -C Hazel/vendor/zlib -f Makefile config=$(zlib_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Hazel/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C Hazel/vendor/Glad -f Makefile config=$(Glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Hazel/vendor/imgui -f Makefile config=$(ImGui_config)
endif

freeimage:
ifneq (,$(freeimage_config))
	@echo "==== Building freeimage ($(freeimage_config)) ===="
	@${MAKE} --no-print-directory -C Hazel/vendor/freeimage -f Makefile config=$(freeimage_config)
endif

FastNoiseSIMD:
ifneq (,$(FastNoiseSIMD_config))
	@echo "==== Building FastNoiseSIMD ($(FastNoiseSIMD_config)) ===="
	@${MAKE} --no-print-directory -C Hazel/vendor/FastNoiseSIMD -f Makefile config=$(FastNoiseSIMD_config)
endif

str:
ifneq (,$(str_config))
	@echo "==== Building str ($(str_config)) ===="
	@${MAKE} --no-print-directory -C Hazel/vendor/ocornut_str -f Makefile config=$(str_config)
endif

libarchive:
ifneq (,$(libarchive_config))
	@echo "==== Building libarchive ($(libarchive_config)) ===="
	@${MAKE} --no-print-directory -C Hazel/vendor/libarchive -f Makefile config=$(libarchive_config)
endif

Hazel: GLFW Glad ImGui freeimage FastNoiseSIMD str zlib libarchive
ifneq (,$(Hazel_config))
	@echo "==== Building Hazel ($(Hazel_config)) ===="
	@${MAKE} --no-print-directory -C Hazel -f Makefile config=$(Hazel_config)
endif

Sandbox: Hazel
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

ImGui\ Test:
ifneq (,$(ImGui_Test_config))
	@echo "==== Building ImGui Test ($(ImGui_Test_config)) ===="
	@${MAKE} --no-print-directory -C ImGui\ Test -f Makefile config=$(ImGui_Test_config)
endif

Sandbox2: Hazel libarchive
ifneq (,$(Sandbox2_config))
	@echo "==== Building Sandbox2 ($(Sandbox2_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox2 -f Makefile config=$(Sandbox2_config)
endif

Game\ Design: Hazel
ifneq (,$(Game_Design_config))
	@echo "==== Building Game Design ($(Game_Design_config)) ===="
	@${MAKE} --no-print-directory -C Game\ Design -f Makefile config=$(Game_Design_config)
endif

clean:
	@${MAKE} --no-print-directory -C Hazel/vendor/zlib -f Makefile clean
	@${MAKE} --no-print-directory -C Hazel/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Hazel/vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C Hazel/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Hazel/vendor/freeimage -f Makefile clean
	@${MAKE} --no-print-directory -C Hazel/vendor/FastNoiseSIMD -f Makefile clean
	@${MAKE} --no-print-directory -C Hazel/vendor/ocornut_str -f Makefile clean
	@${MAKE} --no-print-directory -C Hazel/vendor/libarchive -f Makefile clean
	@${MAKE} --no-print-directory -C Hazel -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean
	@${MAKE} --no-print-directory -C ImGui\ Test -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox2 -f Makefile clean
	@${MAKE} --no-print-directory -C Game\ Design -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   zlib"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   ImGui"
	@echo "   freeimage"
	@echo "   FastNoiseSIMD"
	@echo "   str"
	@echo "   libarchive"
	@echo "   Hazel"
	@echo "   Sandbox"
	@echo "   ImGui Test"
	@echo "   Sandbox2"
	@echo "   Game Design"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"